### ISSUE TITLE
Project 11

### ISSUE THREAD

**Issue by spillman66** [leon1583/BACS350#1]
Hello, your project 11 page doesn't seem to load when I try to open it.

**Comment by leon1583** [comment]
Hey,

Thanks for letting me know! Sorry about that. I've set it from public to private. Did that fix it?

Blessings,
- Caleb Leonard

(1 John 4:10)
________________________________

**Comment by leon1583** [comment]
Project 11 is live at this link: https://findingfocusministries.com/bacs350/slides/index.php

Note: Project 11 is referred to as Project 10 on homepage due to duplication
